export const SEARCH_ITEMS = {
  REQUEST: 'SEARCH_ITEMS_REQUEST',
  SUCCESS: 'SEARCH_ITEMS_SUCCESS',
  FAILED: 'SEARCH_ITEMS_FAILED',
}
export const ITEM_DETAIL = {
  REQUEST: 'ITEM_DETAIL_REQUEST',
  SUCCESS: 'ITEM_DETAIL_SUCCESS',
  FAILED: 'ITEM_DETAIL_FAILED',
}
